// src/frontend/components/diagrams/registry.ts — Technical diagram registry for React Flow.

import { type Edge, MarkerType, type Node } from "@xyflow/react";
import type { CustomNodeData } from "./CustomNodes.js";

export interface DiagramDefinition {
  id: string;
  title: string;
  subtitle: string;
  nodes: Node<CustomNodeData>[];
  edges: Edge[];
  defaultHeight?: number;
}

export const DIAGRAM_REGISTRY: Record<string, DiagramDefinition> = {
  "process-boundaries": {
    id: "process-boundaries",
    title: "Process Boundaries & System Topology",
    subtitle:
      "Strict separation between HTTP/SSE request handling, SQLite WAL persistence, and worker execution.",
    defaultHeight: 560,
    nodes: [
      {
        id: "client-browser",
        type: "custom",
        position: { x: 220, y: 10 },
        data: {
          tag: "Frontend",
          badge: "Browser",
          badgeVariant: "accent",
          title: "Client Browser",
          subtitle: "React 19 SPA + TanStack Query",
          code: "localhost:5173",
          icon: "icon-layers",
          variant: "client",
          hasTopHandle: false,
          hasBottomHandle: true,
        },
      },
      {
        id: "api-server",
        type: "custom",
        position: { x: 220, y: 150 },
        data: {
          tag: "HTTP / SSE Boundary",
          badge: "Fast I/O (<15ms)",
          badgeVariant: "accent",
          title: "API Process",
          subtitle: "Stateless HTTP & SSE Controller",
          code: "src/server.ts (Port 3777)",
          icon: "icon-refresh-cw",
          variant: "service",
          hasTopHandle: true,
          hasBottomHandle: true,
        },
      },
      {
        id: "sqlite-db",
        type: "custom",
        position: { x: 195, y: 300 },
        data: {
          tag: "Storage Layer",
          badge: "WAL Mode",
          badgeVariant: "success",
          title: "SQLite Database",
          subtitle: "Single source of truth on disk",
          code: "x-factory.db",
          items: [
            "runs (workflow truth, revision)",
            "jobs (schedulable units, leases)",
            "events (append-only telemetry)",
          ],
          icon: "icon-shield-check",
          variant: "db",
          hasTopHandle: true,
          hasBottomHandle: true,
        },
      },
      {
        id: "worker-process",
        type: "custom",
        position: { x: 220, y: 500 },
        data: {
          tag: "Worker Boundary",
          badge: "Background",
          badgeVariant: "warning",
          title: "Worker Process",
          subtitle: "Independent Bun engine polling SQLite",
          code: "src/worker.ts",
          icon: "icon-play",
          variant: "worker",
          hasTopHandle: true,
          hasBottomHandle: true,
        },
      },
      {
        id: "pi-agent-sdk",
        type: "custom",
        position: { x: 220, y: 650 },
        data: {
          tag: "AI Execution",
          badge: "Subprocess",
          badgeVariant: "accent",
          title: "Pi Agent SDK",
          subtitle: "Isolated LLM session & worktree tools",
          code: ".worktrees/<projectId>/<runId>",
          icon: "icon-code",
          variant: "agent",
          hasTopHandle: true,
          hasBottomHandle: false,
        },
      },
    ],
    edges: [
      {
        id: "e-client-api",
        source: "client-browser",
        target: "api-server",
        label: "HTTP / SSE Requests",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--accent)",
        },
        style: { stroke: "var(--accent)", strokeWidth: 1.75 },
      },
      {
        id: "e-api-sqlite",
        source: "api-server",
        target: "sqlite-db",
        label: "Atomic Transaction",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--green)",
        },
        style: { stroke: "var(--green)", strokeWidth: 1.75 },
      },
      {
        id: "e-worker-sqlite",
        source: "worker-process",
        target: "sqlite-db",
        label: "Atomic Claim / Heartbeat",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "#a371f7",
        },
        style: { stroke: "#a371f7", strokeWidth: 1.75 },
      },
      {
        id: "e-worker-pi",
        source: "worker-process",
        target: "pi-agent-sdk",
        label: "Spawn Isolated Session",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "#f0883e",
        },
        style: { stroke: "#f0883e", strokeWidth: 1.75 },
      },
    ],
  },

  "worker-lease-model": {
    id: "worker-lease-model",
    title: "Worker Lease Lifecycle & Crash Recovery",
    subtitle:
      "Database-backed lease locks: 30s claim, 10s heartbeats, and automatic stale job reclamation.",
    defaultHeight: 460,
    nodes: [
      {
        id: "lease-pending",
        type: "custom",
        position: { x: 30, y: 60 },
        data: {
          tag: "State 0",
          badge: "Queue",
          badgeVariant: "warning",
          title: "Job: Pending",
          subtitle: "Waiting for available worker",
          icon: "icon-clock",
          variant: "state-pending",
          hasTopHandle: false,
          hasRightHandle: true,
          hasBottomHandle: false,
        },
      },
      {
        id: "lease-claimed",
        type: "custom",
        position: { x: 370, y: 60 },
        data: {
          tag: "State 1",
          badge: "Active",
          badgeVariant: "accent",
          title: "Job: Claimed",
          subtitle: "Worker sets lease_until = +30s",
          code: "lease_until = datetime('now', '+30s')",
          icon: "icon-refresh-cw",
          variant: "state-claimed",
          hasLeftHandle: true,
          hasBottomHandle: true,
        },
      },
      {
        id: "lease-heartbeat",
        type: "custom",
        position: { x: 200, y: 230 },
        data: {
          tag: "Healthy Path",
          badge: "Every 10s",
          badgeVariant: "success",
          title: "Heartbeat Loop",
          subtitle: "Worker renews lease +30s while active",
          icon: "icon-check-circle-2",
          variant: "state",
          hasTopHandle: true,
          hasBottomHandle: true,
        },
      },
      {
        id: "lease-crash",
        type: "custom",
        position: { x: 540, y: 230 },
        data: {
          tag: "Failure Path",
          badge: "Timeout",
          badgeVariant: "danger",
          title: "Worker Crash / Stall",
          subtitle: "Heartbeat ceases; lease expires (>30s)",
          icon: "icon-alert-circle",
          variant: "state-expired",
          hasTopHandle: true,
          hasBottomHandle: true,
        },
      },
      {
        id: "lease-completed",
        type: "custom",
        position: { x: 200, y: 370 },
        data: {
          tag: "Terminal",
          badge: "Success",
          badgeVariant: "success",
          title: "Job: Completed",
          subtitle: "FSM transitions to next pipeline stage",
          icon: "icon-check",
          variant: "state-completed",
          hasTopHandle: true,
          hasBottomHandle: false,
        },
      },
      {
        id: "lease-reclaimed",
        type: "custom",
        position: { x: 540, y: 370 },
        data: {
          tag: "Recovery",
          badge: "Retry",
          badgeVariant: "warning",
          title: "Stale Job Reclaimed",
          subtitle: "Another worker increments attempt & retries",
          icon: "icon-refresh-cw",
          variant: "state-pending",
          hasTopHandle: true,
          hasBottomHandle: false,
        },
      },
    ],
    edges: [
      {
        id: "e-pending-claimed",
        source: "lease-pending",
        sourceHandle: "right",
        target: "lease-claimed",
        targetHandle: "left",
        label: "Atomic Lease Claim (30s)",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--accent)",
        },
        style: { stroke: "var(--accent)", strokeWidth: 1.75 },
      },
      {
        id: "e-claimed-heartbeat",
        source: "lease-claimed",
        target: "lease-heartbeat",
        label: "Active Stage Run",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--green)",
        },
        style: { stroke: "var(--green)", strokeWidth: 1.75 },
      },
      {
        id: "e-claimed-crash",
        source: "lease-claimed",
        target: "lease-crash",
        label: "No Heartbeat Emitted",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--red)",
        },
        style: {
          stroke: "var(--red)",
          strokeWidth: 1.75,
          strokeDasharray: "4,4",
        },
      },
      {
        id: "e-heartbeat-completed",
        source: "lease-heartbeat",
        target: "lease-completed",
        label: "Stage Succeeded",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--green)",
        },
        style: { stroke: "var(--green)", strokeWidth: 1.75 },
      },
      {
        id: "e-crash-reclaimed",
        source: "lease-crash",
        target: "lease-reclaimed",
        label: "Lease Expired (>30s)",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--yellow)",
        },
        style: { stroke: "var(--yellow)", strokeWidth: 1.75 },
      },
    ],
  },

  "event-distribution": {
    id: "event-distribution",
    title: "Real-Time Telemetry & Event Distribution",
    subtitle:
      "Decoupled event pipeline: background workers persist durable events to SQLite, and SSE registry streams real-time updates to connected clients.",
    defaultHeight: 460,
    nodes: [
      {
        id: "ev-worker",
        type: "custom",
        position: { x: 30, y: 100 },
        data: {
          tag: "Producer",
          badge: "Worker",
          badgeVariant: "warning",
          title: "Worker Process",
          subtitle: "Executes pipeline stages",
          code: "src/worker.ts",
          icon: "icon-play",
          variant: "worker",
          hasTopHandle: false,
          hasBottomHandle: false,
          hasRightHandle: true,
        },
      },
      {
        id: "ev-bus",
        type: "custom",
        position: { x: 350, y: 100 },
        data: {
          tag: "Dispatcher",
          badge: "SSE Stream",
          badgeVariant: "accent",
          title: "SSERegistry",
          subtitle: "Central decoupling layer for subscribers",
          code: "src/http/sse-registry.ts",
          icon: "icon-layers",
          variant: "service",
          hasLeftHandle: true,
          hasRightHandle: true,
          hasBottomHandle: true,
          hasTopHandle: false,
        },
      },
      {
        id: "ev-api",
        type: "custom",
        position: { x: 670, y: 100 },
        data: {
          tag: "Gateway",
          badge: "SSE Stream",
          badgeVariant: "accent",
          title: "API Process",
          subtitle: "Dispatches events to clients",
          code: "src/server.ts",
          icon: "icon-refresh-cw",
          variant: "service",
          hasLeftHandle: true,
          hasBottomHandle: true,
          hasTopHandle: false,
          hasRightHandle: false,
        },
      },
      {
        id: "ev-sqlite",
        type: "custom",
        position: { x: 350, y: 290 },
        data: {
          tag: "Durable Sink",
          badge: "SQLite Table",
          badgeVariant: "success",
          title: "events Table",
          subtitle: "Append-only historical audit trail",
          code: "x-factory.db",
          icon: "icon-shield-check",
          variant: "db",
          hasTopHandle: true,
          hasBottomHandle: false,
        },
      },
      {
        id: "ev-browser",
        type: "custom",
        position: { x: 670, y: 290 },
        data: {
          tag: "Subscriber",
          badge: "Client UI",
          badgeVariant: "accent",
          title: "Browser Client",
          subtitle: "EventSource listener updates TanStack cache",
          icon: "icon-layers",
          variant: "client",
          hasTopHandle: true,
          hasBottomHandle: false,
        },
      },
    ],
    edges: [
      {
        id: "e-worker-bus",
        source: "ev-worker",
        sourceHandle: "right",
        target: "ev-bus",
        targetHandle: "left",
        label: "1. Emit Telemetry Event",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "#a371f7",
        },
        style: { stroke: "#a371f7", strokeWidth: 1.75 },
      },
      {
        id: "e-bus-sqlite",
        source: "ev-bus",
        sourceHandle: "bottom",
        target: "ev-sqlite",
        targetHandle: "top",
        label: "2. Persist to Disk",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--green)",
        },
        style: { stroke: "var(--green)", strokeWidth: 1.75 },
      },
      {
        id: "e-bus-api",
        source: "ev-bus",
        sourceHandle: "right",
        target: "ev-api",
        targetHandle: "left",
        label: "3. In-Memory Fan-Out",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--accent)",
        },
        style: { stroke: "var(--accent)", strokeWidth: 1.75 },
      },
      {
        id: "e-api-browser",
        source: "ev-api",
        sourceHandle: "bottom",
        target: "ev-browser",
        targetHandle: "top",
        label: "4. SSE Stream to UI",
        type: "smoothstep",
        markerEnd: {
          type: MarkerType.ArrowClosed,
          width: 14,
          height: 14,
          color: "var(--accent)",
        },
        style: { stroke: "var(--accent)", strokeWidth: 1.75 },
      },
    ],
  },
};
