// scripts/generate-schema-doc.ts — Regenerates the structural section of
// docs/reference/database-schema.md from the SQL migrations.
//
// The migrations are the source of truth for structure; the doc's prose
// outside the generated markers carries intent and is never touched.
//
// Usage:
//   bun scripts/generate-schema-doc.ts          rewrite the generated section
//   bun scripts/generate-schema-doc.ts --check  exit 1 if the doc is stale

import { Database } from "bun:sqlite";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { loadMigrations, runMigrations } from "../src/db/migrator.js";

const DOC_PATH = path.join(
  import.meta.dir,
  "..",
  "docs",
  "reference",
  "database-schema.md",
);
const START = "<!-- schema:generated:start -->";
const END = "<!-- schema:generated:end -->";

interface ColumnInfo {
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
}

interface ForeignKeyInfo {
  from: string;
  table: string;
  to: string;
  on_delete: string;
}

interface IndexInfo {
  name: string;
  unique: number;
  origin: string;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function renderTable(db: Database, table: string): string {
  const columns = db
    .query(`PRAGMA table_info(${JSON.stringify(table)})`)
    .all() as ColumnInfo[];
  const foreignKeys = db
    .query(`PRAGMA foreign_key_list(${JSON.stringify(table)})`)
    .all() as ForeignKeyInfo[];
  const indexes = db
    .query(`PRAGMA index_list(${JSON.stringify(table)})`)
    .all() as IndexInfo[];

  const fkByColumn = new Map(foreignKeys.map((fk) => [fk.from, fk]));

  const lines = [
    `### Table: \`${table}\``,
    "",
    "| Column | Type | Null | Default | Key | References |",
    "|---|---|---|---|---|---|",
  ];
  for (const col of columns) {
    const fk = fkByColumn.get(col.name);
    const ref = fk
      ? `${fk.table}(${fk.to})${fk.on_delete !== "NO ACTION" ? ` ON DELETE ${fk.on_delete}` : ""}`
      : "";
    lines.push(
      `| \`${col.name}\` | ${col.type || "—"} | ${col.notnull ? "NOT NULL" : "NULL"} | ${
        col.dflt_value === null ? "" : `\`${escapeCell(col.dflt_value)}\``
      } | ${col.pk ? "PK" : ""} | ${ref} |`,
    );
  }

  const named = indexes.filter((idx) => idx.origin !== "pk");
  if (named.length > 0) {
    lines.push("", "Indexes and constraints:", "");
    for (const idx of named) {
      const cols = (
        db
          .query(`PRAGMA index_info(${JSON.stringify(idx.name)})`)
          .all() as Array<{ name: string }>
      ).map((c) => c.name);
      const kind = idx.unique ? "UNIQUE" : "INDEX";
      const label = idx.origin === "c" ? `\`${idx.name}\`` : "(inline)";
      lines.push(`- ${kind} ${label} on (${cols.join(", ")})`);
    }
  }

  return lines.join("\n");
}

function generateSchemaSection(): string {
  const db = new Database(":memory:");
  db.exec("PRAGMA foreign_keys = ON;");
  const migrations = loadMigrations();
  runMigrations(db, migrations);

  const tables = (
    db
      .query(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
      )
      .all() as Array<{ name: string }>
  ).map((row) => row.name);

  const parts = [
    START,
    "<!-- Generated by `bun run docs:schema` from src/db/migrations. Do not edit by hand. -->",
    "",
    "### Migrations",
    "",
    ...migrations.map(
      (m) =>
        `- **v${m.version}** \`${m.version.toString().padStart(3, "0")}_${m.name}.sql\``,
    ),
    "",
    ...tables.flatMap((table) => [renderTable(db, table), ""]),
    END,
  ];
  db.close();
  return parts.join("\n");
}

function main(): void {
  const check = process.argv.includes("--check");
  const doc = readFileSync(DOC_PATH, "utf-8");
  const start = doc.indexOf(START);
  const end = doc.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    console.error(`Markers ${START} / ${END} not found in ${DOC_PATH}`);
    process.exit(1);
  }

  const next =
    doc.slice(0, start) + generateSchemaSection() + doc.slice(end + END.length);

  if (check) {
    if (next !== doc) {
      console.error(
        "docs/reference/database-schema.md is out of date with the migrations. Run `bun run docs:schema`.",
      );
      process.exit(1);
    }
    console.log("Schema doc is up to date.");
    return;
  }

  if (next !== doc) {
    writeFileSync(DOC_PATH, next);
    console.log("Regenerated docs/reference/database-schema.md");
  } else {
    console.log("Schema doc already up to date.");
  }
}

if (import.meta.main) main();
