// src/types.ts — Core domain models and workflow types for X-Factory.

export type {
  AzureTrackerConfig,
  CommandResult,
  ConfigureGitIdentityResult,
  Finding,
  GitHubTrackerConfig,
  GitIdentity,
  GitIdentityScope,
  ImplementationContext,
  IssueTrackerProvider,
  JiraTrackerConfig,
  KnowledgeRepository,
  Project,
  ProjectConnection,
  ProjectIssueTracker,
  ProjectReadiness,
  ProjectRepository,
  PullRequest,
  RepositoryCommands,
  RepositoryReadiness,
  RepositoryRole,
  ReviewResult,
  Run,
  RunEvent,
  RunEventPayload,
  RunStatus,
  Ticket,
  VerificationResult,
  WorkflowStage,
} from "./shared/types.js";
